### ISSUE TITLE
Many messageKeys, one callback

### ISSUE THREAD

**Issue by stefangeneralao** [rasmuselmgren/sp-bot#12]
**Background:**
Currently `addMessageCreateEvent` only accepts `messageKey` as a string.

**Solution:**
Implement the possibility to pass `messageKey` as an array to `addMessageCreateEvent`.

`addMessageCreateEvent` should still accept `messageKey` as a single string.

**Consider:**
Implement a `MessageKey` class that would be passed to `addMessageCreateEvent`, e.g., `addMessageCreateEvent(new MessageKey('banana'), () => 'apple')`

**Comment by rasmuselmgren** [comment]
This issue is probably outdated?

**Comment by stefangeneralao** [comment]
Outdated
